version: '3.9'

networks:
  backend:
    name: backend-network
    driver: bridge

services:
  auth-service:
    image: auth.service:local
    build: .
    container_name: auth-service
    restart: unless-stopped
    environment:
      - PORT=80
      - NODE_ENV=production
    env_file:
      - secrets.env
    networks:
      - backend
    expose:
      - 80
