version: '3'
networks:
  default:
    external:
      name: home_network
services:
  auth-service:
    build: .
    image: 'auth.service:local'
    container_name: auth-service
    restart: unless-stopped
    environment:
      - PORT=80
      - NODE_ENV=production
    env_file:
      - secrets.env
    expose:
      - 80
